import json
import re
from pathlib import Path
from typing import Any

class ProjectMemoryCompiler:
    """Compiles a readable project knowledge pack from the workspace without requiring an LLM."""
    def __init__(self, workspace_root: str, memory_root: str):
        self.workspace=Path(workspace_root).resolve(); self.memory_root=Path(memory_root).resolve(); self.memory_root.mkdir(parents=True,exist_ok=True)
        self.ignore={".git",".venv","node_modules","__pycache__",".pytest_cache","dist","build",".next"}

    def compile(self, project_name: str | None = None) -> dict[str, Any]:
        name=project_name or self.workspace.name or "project"; out=self.memory_root/"projects"/name; out.mkdir(parents=True,exist_ok=True)
        files=[]; headings=[]; decisions=[]; experiments=[]; failures=[]
        for p in self.workspace.rglob("*"):
            if not p.is_file() or any(x in self.ignore for x in p.parts): continue
            rel=str(p.relative_to(self.workspace))
            rec={"path":rel,"bytes":p.stat().st_size,"ext":p.suffix.lower()}; files.append(rec)
            if p.suffix.lower() in {".md",".txt",".py",".ts",".tsx",".js"}:
                try: text=p.read_text(encoding="utf-8",errors="replace")[:400_000]
                except OSError: continue
                for line in text.splitlines():
                    s=line.strip()
                    if re.match(r"^#{1,4}\s+",s): headings.append(f"- {rel}: {re.sub(r'^#{1,4}\\s+','',s)[:160]}")
                    low=s.lower()
                    if any(k in low for k in ("decision:","decided:","architecture decision","adr")): decisions.append(f"- {rel}: {s[:220]}")
                    if any(k in low for k in ("experiment:","hypothesis:","benchmark:","ablation:")): experiments.append(f"- {rel}: {s[:220]}")
                    if any(k in low for k in ("known issue","failure:","failed:","todo:","fixme:")): failures.append(f"- {rel}: {s[:220]}")
        overview=f"# {name} — Project Overview\n\nGenerated by Catalyst from the current workspace.\n\n## Workspace\n- Root: `{self.workspace}`\n- Files: {len(files)}\n- Total bytes: {sum(x['bytes'] for x in files)}\n\n## Important headings\n{chr(10).join(headings[:250]) or '- None detected'}\n"
        (out/"overview.md").write_text(overview,encoding="utf-8")
        (out/"architecture.md").write_text("# Architecture\n\n## Detected structure\n"+"\n".join(f"- `{x['path']}` ({x['bytes']} bytes)" for x in files[:500]),encoding="utf-8")
        (out/"decisions.md").write_text("# Decisions\n\n"+("\n".join(dict.fromkeys(decisions)) or "- None detected yet."),encoding="utf-8")
        (out/"experiments.md").write_text("# Experiments\n\n"+("\n".join(dict.fromkeys(experiments)) or "- None detected yet."),encoding="utf-8")
        (out/"failures.md").write_text("# Known Issues / Failures\n\n"+("\n".join(dict.fromkeys(failures)) or "- None detected yet."),encoding="utf-8")
        manifest={"project":name,"root":str(self.workspace),"file_count":len(files),"files":files[:2000]}; (out/"manifest.json").write_text(json.dumps(manifest,indent=2),encoding="utf-8")
        return {"project":name,"output":str(out.relative_to(self.memory_root.parent if self.memory_root.parent.exists() else self.memory_root)),"files":len(files),"decisions":len(decisions),"experiments":len(experiments),"failures":len(failures)}
